### ISSUE TITLE
Extract function

### ISSUE THREAD

**Issue by valis** [JetBrains/intellij-arend#104]
We often need to prove something about an expression by induction. In this case, we need to add a new function and apply it to the given expression. This can be done by the IDE.

For example, let's say we have the following code:
```
\open Nat(+)
\func foo (x y z : Nat) : x + y = z => {?}
```
If we want to prove `foo` by induction on `x + y`, then we can write this expression in the goal (or the expression can be defined in the dialog) and invoke this intention, which will generate the following code:

```
\open Nat(+)
\func foo (x y z : Nat) : x + y = z => aux z (x + y)
  \where
    \func aux (z n : Nat) : n = z \elim n
      | 0 => {?}
      | suc n => {?}
```

The intention should show a dialog, in which the user can choose the name of the generated function (`aux` in this example), variables which will be added to the function (`z` in this example), and where it should be put.

Also, this intention can be also used to generate auxiliary functions defined not by pattern matching. This can also be configured in the dialog. In this case, the intention will produce the following code:
```
\open Nat(+)
\func foo (x y z : Nat) : x + y = z => aux z (x + y)
  \where
    \func aux (z n : Nat) : n = z => {?}
```

This intention can also be used to extract an expression.
Let's say that we have the following code:
```
\open Nat(+,*)
\func foo (x y z : Nat) => z * (x + y * z)
```

Then we can select `x + y * z` and invoke the intention which will generate the following code (after showing the same dialog):
```
\open Nat(+,*)
\func foo (x y z : Nat) => z * aux z x y
  \where
    \func aux (z x y : Nat) => x + y * z
```

Also, this intention can be used to transform a `\case` expression into a call of an auxiliary function.

**Comment by ice1000** [comment]
This is called "helper function" in Agda, invoked via Ctrl-C Ctrl-H
