### ISSUE TITLE
Show the result of a meta definition

### ISSUE THREAD

**Issue by valis** [JetBrains/intellij-arend#113]
Implement an action that show the result of the meta definition under the cursor.

**Comment by ice1000** [comment]
Already implemented in some sense:
![image](https://user-images.githubusercontent.com/16398479/76045798-1e504c00-5f2c-11ea-8e97-6c8a10b823a4.png)

**Comment by valis** [comment]
"Meta definitions" are tactics, not "meta variables"

**Comment by ice1000** [comment]
Oh

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/76053165-53639b00-5f3a-11ea-8ab8-66e1447562ba.png)
How 'bout this?

**Comment by ice1000** [comment]
However, normalizing it to WHNF doesn't show a well-typed expr:

![image](https://user-images.githubusercontent.com/16398479/76053310-c1a85d80-5f3a-11ea-87e9-794afddb0930.png)

**Comment by valis** [comment]
It would be convenient to show the non-normalized result.

It does not type-check because it doesn't print implicit arguments for `Equiv`.
