### ISSUE TITLE
Debugger for Arend

### ISSUE THREAD

**Issue by valis** [JetBrains/intellij-arend#168]

**Comment by valis** [comment]
It should step through code showing intermediate type-checking state similar to coq's interactive mode.

**Comment by marat-rkh** [comment]
Implemented, we call "tracer", not "debugger". Currently, you can:
* start it via a pop-up menu on declarations and expressions
* step through the expressions back and forth, jump to a specifict expression via "Run to Cursor", and stop early if needed
* inspect the stack and the context in the editor view at each tracing step.

https://user-images.githubusercontent.com/5653229/159868616-20589af7-80b2-4dfc-b524-de29f2ce1878.mp4

Thanks @ice1000 for the initial implementation, the current implementation is based on it)
