### ISSUE TITLE
Missing completions

### ISSUE THREAD

**Issue by ice1000** [JetBrains/intellij-arend#198]
![image](https://user-images.githubusercontent.com/16398479/85120805-54ed7080-b256-11ea-996b-d10da68eb040.png)

Missing `\import`, `\func`, etc.

**Comment by sxhya** [comment]
Hmm. Is it only in repl? How can I reproduce that?

**Comment by ice1000** [comment]
Did you mean we intentionally disable such completion?

**Comment by sxhya** [comment]
Currently we add statement completion variants (`\import`, `\func` etc) only if there is at least one CRLF delimiter before the cursor. Similarly, If there are two CRLFs before the cursor we add ONLY statement completion variants (that is we do not add expression completion variants).

**Comment by ice1000** [comment]
Gotcha
