### ISSUE TITLE
Save history in REPL

### ISSUE THREAD

**Issue by ice1000** [JetBrains/intellij-arend#209]
As title.

**Comment by sxhya** [comment]
Hi, @ice1000! I implemented feature `:show_context` and `:reset_context` for REPL which prints all the earlier typed in definitions/import commands which affect the state of REPL. Could you elaborate whether you meant that or something else?

**Comment by ice1000** [comment]
> Hi, @ice1000! I implemented feature `:show_context` and `:reset_context` for REPL which prints all the earlier typed in definitions/import commands which affect the state of REPL. Could you elaborate whether you meant that or something else?

Like when you start the repl and press up, you'll see the last command you used in the previous session. Jline3 has a feature for that.

**Comment by sxhya** [comment]
It looks like history feature works in current IDE without additional work.
