### ISSUE TITLE
Support semantic highlighting

### ISSUE THREAD

**Issue by ice1000** [JetBrains/intellij-arend#216]
As title.

**Comment by valis** [comment]
What's that?

**Comment by ice1000** [comment]
https://blog.jetbrains.com/pycharm/2017/01/make-sense-of-your-variables-at-a-glance-with-semantic-highlighting/

**Comment by ice1000** [comment]
It's basically this class: https://github.com/JetBrains/intellij-community/blob/master/platform/analysis-impl/src/com/intellij/codeInsight/daemon/RainbowVisitor.java

**Comment by ice1000** [comment]
Reference impl: [Java](https://github.com/JetBrains/intellij-community/blob/master/java/java-impl/src/com/intellij/codeInsight/daemon/JavaRainbowVisitor.java) and [Rust](https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/ide/highlight/RsRainbowVisitor.kt)

**Comment by ice1000** [comment]
Enable via ![image](https://user-images.githubusercontent.com/16398479/94062887-ddf9e200-fe19-11ea-9f11-c172a4dd1813.png)

**Comment by ice1000** [comment]
Effect (help distinguish bindings and constructor references)
![image](https://user-images.githubusercontent.com/16398479/94062921-e81be080-fe19-11ea-9148-b11f66e37492.png)
