### ISSUE TITLE
Uninformative highlighting for lhs of the dot operator

### ISSUE THREAD

**Issue by ice1000** [JetBrains/intellij-arend#242]
![image](https://user-images.githubusercontent.com/16398479/95650007-67e0c500-0b13-11eb-8fe4-8adfb6ece10e.png)

The LHS is colored purple, but what does that mean? Is that semiring thing a module? Is that an instance? Is that a function? Is that a local variable? It doesn't tell me anything.

**Comment by valis** [comment]
I think it's fine
