### ISSUE TITLE
A plugin error happens with new IDEA

### ISSUE THREAD

**Issue by zhelenskiy** [JetBrains/intellij-arend#248]
Plugin error: Plugin 'Arend' (version '1.5.0') is not compatible with the current version of the IDE, because it requires build 202.* or older but the current build is IU-203.7148.57

**Comment by ice1000** [comment]
You can try to build this project yourself. The master branch is compatible with 2021.1.

See #247

**Comment by zhelenskiy** [comment]
But what about updating the published version? Building it myself is a workaround but not a proper solution.

**Comment by ice1000** [comment]
> But what about updating the published version? Building it myself is a workaround but not a proper solution.

I think you need to wait for the next release.

**Comment by ice1000** [comment]
[Arend-1.5.1.zip](https://github.com/JetBrains/intellij-arend/files/6004416/Arend-1.5.1.zip)

Here's what I can do... for now.

**Comment by zhelenskiy** [comment]
And when is it expected to appear? Is there any approximate date?

**Comment by ice1000** [comment]
> And when is it expected to appear? Is there any approximate date?

I don't know, but you can keep an eye on https://github.com/JetBrains/Arend/milestone/5.

**Comment by valis** [comment]
> And when is it expected to appear? Is there any approximate date?

It should be ready the next weak.
