### ISSUE TITLE
Traditional indentation

### ISSUE THREAD

**Issue by suhr** [JetBrains/intellij-arend#251]
For a let expression, the arend plugin applies a Haskell style indentation, aligning the indentation to `sum_comm`:

```arend
\func sum (x : MSet Int) : Int
  | nil => 0
  | :: a x => a + sum x
  | comm x y tail i =>
    \let sum_comm : x + (y + sum tail) = y + (x + sum tail) =>
           x + (y + sum tail) ==< inv +-assoc >==
           (x + y) + sum tail ==< pmap (__ + sum tail) +-comm >==
           (y + x) + sum tail ==< +-assoc >==
           y + (x + sum tail) `qed
    \in sum_comm @ i
```

It would be nice to also have traditional indentation, which align the indentation to `\let` instead:

```arend
\func sum (x : MSet Int) : Int
  | nil => 0
  | :: a x => a + sum x
  | comm x y tail i =>
    \let sum_comm : x + (y + sum tail) = y + (x + sum tail) =>
      x + (y + sum tail) ==< inv +-assoc >==
      (x + y) + sum tail ==< pmap (__ + sum tail) +-comm >==
      (y + x) + sum tail ==< +-assoc >==
      y + (x + sum tail) `qed
    \in sum_comm @ i

```

**Comment by sxhya** [comment]
I have changed the behavior of the code formatter. The default indentation now is as in the second code piece. However, if a let expression has more than 1 "let clause" (i. e. subexpression of the form `| x : Type => expr` ) then we use the behavior as in the first code piece.
