### ISSUE TITLE
Consider adding predefined live templates

### ISSUE THREAD

**Issue by marat-rkh** [JetBrains/intellij-arend#252]
Users can define live templates in "Preferences | Editor | Live Templates". For example, I have the following ones:

<img width="925" alt="Screen Shot 2021-03-19 at 2 23 55 PM" src="https://user-images.githubusercontent.com/5653229/111773505-4f918500-88bf-11eb-952a-ef71d3e345ea.png">

They work like this:

![live-templ](https://user-images.githubusercontent.com/5653229/111773572-63d58200-88bf-11eb-8141-eb87c1652c3e.gif)

I find them useful for 2 reasons:
1. They speed up the typing by generating the boilerplate code.
2. They help me learn the language. As a newcomer, I do not remember the exact syntax of various language constructs, and templates handle that.

I think having them predefined in the plugin could be useful. Other languages do that too. Arend can have such templates for many keywords like `\func`, `\let`, `\Pi`, etc.

**Comment by ice1000** [comment]
Can you share your live templates in your settings xml? We could bundle it directly

**Comment by marat-rkh** [comment]
@ice1000 Sorry, I have missed your comment. I am not sure if my own templates are good enough for direct bundling. I will think more about them and templates in general and get back here later)

**Comment by marat-rkh** [comment]
BTW, there is a very similar thing for Coq in Emacs (most likely provided by company-coq extension).

![Kapture 2021-12-06 at 15 29 41](https://user-images.githubusercontent.com/5653229/144846478-44c07e66-c7e3-43a3-99e1-2b26b7e830c4.gif)

**Comment by ice1000** [comment]
Wow, the UX is so similar to live templates!
