### ISSUE TITLE
Smarter highlighting and quickfixing of nameresolver errors

### ISSUE THREAD

**Issue by sxhya** [JetBrains/intellij-arend#26]
When the same identifier is imported from two modules, it would be better to highlight only the imported identifiers and not the namespace commands themselves. Also it would be great to have quickfixes proposed in this situation (e.g. rename identifier f into something user-defined).

--A.vc and B.vc both implement function f;
\import A (f) -- suggested quickfix: rename f 
\import B -- suggested quickfix: add f to hiding list (or suggest renaming f)

**Comment by valis** [comment]
The first half is fixed.

**Comment by valis** [comment]
The error is DuplicateOpenedName.

Before:
```
\module M1 \where {
  \func foo => 0
}

\module M2 \where {
  \func foo => 0
  \func baz => 0
}

\open M1
\open M2(foo)
```

After:
```
\open M1
\open M2(foo \as foo1)
```

Before:
```
\open M1
\open M2
```

After:
```
\open M1
\open M2(foo \as foo1)
```

Before:
```
\open M1
\open M2(baz \as foo)
```

After:
```
\open M1
\open M2(baz \as foo1)
```

**Comment by valis** [comment]
The same quick fix can be implemented for ExistingOpenedNameError

Before:
```
\module M \where {
  \func foo => 0
  \func baz => 0
}

\func foo => 0

\open M(foo)
```

After:
```
\open M(foo \as foo1)
```

Before:
```
\open M(baz \as foo)
```

After:
```
\open M(baz \as foo1)
```
