### ISSUE TITLE
"Show implemented fields" doesn't always work

### ISSUE THREAD

**Issue by marat-rkh** [JetBrains/intellij-arend#269]
Open `Equiv.ard` in `arend-lib` and call "Class Hierarchy" on `QEquiv`:

<img width="1214" alt="Screen Shot 2021-05-13 at 12 00 40 PM" src="https://user-images.githubusercontent.com/5653229/118104015-41557600-b3e3-11eb-9fad-0f5d650f540f.png">

I expect to see `sec` as implemented field, but it is not shown at all.

Note that it works in other cases. For example, it works for `SplitMono` in `Category.ard`:

<img width="1216" alt="Screen Shot 2021-05-13 at 12 02 21 PM" src="https://user-images.githubusercontent.com/5653229/118104204-7feb3080-b3e3-11eb-811f-3efed9606920.png">

**Comment by sxhya** [comment]
Can't reproduce
