### ISSUE TITLE
New inspection: Redundant parameter name

### ISSUE THREAD

**Issue by marat-rkh** [JetBrains/intellij-arend#288]
Consider a declaration:

<img width="850" alt="Screen Shot 2021-08-15 at 2 02 36 PM" src="https://user-images.githubusercontent.com/5653229/129476268-b2575af9-376c-4c33-9a42-f23d805333ec.png">

Parameter name `d` is redundant here and can be replaced with `_`. This could simplify the declaration and improve readability as `_` stresses the fact that there is no dependencies on the parameter in the signature.

IDE could have an inspection that detects such cases and suggest the replacement.

**Comment by mmagic-boy** [comment]
Same could be done for names in clauses:

<img width="808" alt="Screen Shot 2021-08-15 at 2 56 54 PM" src="https://user-images.githubusercontent.com/5653229/129477736-59bb1b02-06bd-4d86-a824-0e10082fb905.png">
