### ISSUE TITLE
Allow creating Arend project without Java SDK

### ISSUE THREAD

**Issue by marat-rkh** [JetBrains/intellij-arend#310]
When I create Arend project and I have some Java SDK on my machine, it is selected in the project wizard and I cannot unselect it:

<img width="811" alt="Screen Shot 2021-09-22 at 12 05 13 PM" src="https://user-images.githubusercontent.com/5653229/134315265-f7006343-d09a-46a2-9299-f92e5d9a3127.png">

As a result, it is added to External Libraries, affects indexing time and adds a lot of java files when I invoke "Navigate | File" or "Navigate | Symbol":

<img width="838" alt="Screen Shot 2021-09-22 at 12 00 49 PM" src="https://user-images.githubusercontent.com/5653229/134315571-0f1bf9fa-7eb6-4b1b-b388-03dee334d096.png">

I think it would be nice to allow unselecting it in the wizard. I would even make it unselected by default, as it is not needed unless you want to write a language extension.

**Comment by ice1000** [comment]
> unless you want to write a language extension.

Or you wanna debug the type checking. 🤣

**Comment by marat-rkh** [comment]
Fixed in 388eca3. Now there is `<No SDK>` item available.

<img width="827" alt="Screen Shot 2022-01-20 at 6 20 04 PM" src="https://user-images.githubusercontent.com/5653229/150367684-635fb47c-691a-4e13-bc8b-3b5f71d34233.png">

**Comment by ice1000** [comment]
It would be good to show the usages of a jdk in the wizard

**Comment by marat-rkh** [comment]
You mean to explain that it is needed to write language extensions?

**Comment by ice1000** [comment]
> You mean to explain that it is needed to write language extensions?

As well as debugging

**Comment by marat-rkh** [comment]
This is actually a good idea :) I have created #351 for it.
