### ISSUE TITLE
Support Proof Search for Arend

### ISSUE THREAD

**Issue by knisht** [JetBrains/intellij-arend#319]
All proof assistants have a common problem: once some theorem is proven and used, its existence may be forgotten. I often found myself re-proving the same statement over and over, just because I couldn't recall the location of the first proven theorem.

Proof assistants like Coq support Proof Search: a directive, that searches all theorems that state something about required definition.

Obviously, IDEA can help with it via its "Find Usages" feature, which doesn't work currently for Arend. But it will show every occurrence of the definition, and this action is very slow.

The solution I propose is to use a ["Structural Search"](https://www.jetbrains.com/help/idea/structural-search-and-replace.html) feature. 

- It can be adapted to show only theorems where the definition occurs in codomain. Having this restriction in mind, SSR for Arend may deal with stubs only (I suppose), and it should speedup the feature.
- As it already supports some scripting, it may be implemented to search for patterns (Like, `$x$ + $y$ = $y$ + $x$`, if the user doesn't remember the name of `+-comm`). 
- (To be discussed) It may support search up to normalization of the term (maybe a synthetic example, but it will roughly look like this: the user searches for `length (($x$ :: []) ++ $l$)` and gets a lemma about `length (a :: list) = suc (length list)`).

**Comment by valis** [comment]
What do you mean "Find Usages" doesn't work for Arend? It does.

**Comment by knisht** [comment]
Oh, indeed. I usually invoke it by right-clicking on the name of the definition, not by a short-cut.

**Comment by ice1000** [comment]
Find usages doesn't work in the way Java does. If you Ctrl+click on a definition, in Java it finds usages, but in Arend it does nothing (but jump to the beginning of the name identifier).

**Comment by ice1000** [comment]
Also, a nitpick on terminology: "proof search" normally means some heuristics to *generate* a proof given an environment, not to *search* for lemmata. In Lean I recall they use the phrase 'library search'
