### ISSUE TITLE
Consider showing goals and errors in separate windows

### ISSUE THREAD

**Issue by marat-rkh** [JetBrains/intellij-arend#336]
We have "Arend Errors" window that shows both type checking errors and goals. There is one particular scenario when it could be inconvenient to use:
1. Place a caret at a goal to see what you need to prove in "Arend Errors".
2. Start typing something to fill the goal. As long as your code is not complete, you will get type checking errors in "Arend Errors". At this point, you lose the information about the goal you prove.

One way to solve this issue is to "Pin" the goal. This is fine, but has its disadvantages:
1. You need to know about this action and invoke it manually.
2. You will not be able to see the errors as you type.

We could try to improve the situation by showing errors and goals in two separate windows (or, rather, in two separate sections of the same window). The window for goals should show the last goal that the caret was placed on.

**Comment by knisht** [comment]
Actually, goal expressions allow achieving something similar. I'm talking about `{?(foo bar baz)}`. 
Although I rarely use them, as they are inconvenient for nested goals (`{?(foo bar {?})}`).

**Comment by marat-rkh** [comment]
Also, I see that as I start typing `()`, I lose the information in the "Arend Errors":

![goal-expression](https://user-images.githubusercontent.com/5653229/141077345-865d1113-4c2a-4076-bcef-e0375d1e7452.gif)

**Comment by ice1000** [comment]
> Also, I see that as I start typing `()`, I lose the information in the "Arend Errors":
> 
> ![goal-expression](https://user-images.githubusercontent.com/5653229/141077345-865d1113-4c2a-4076-bcef-e0375d1e7452.gif)
> 
> 
> 

The right-bottom right window lmao

**Comment by marat-rkh** [comment]
Implemented. Major changes:
1. Goals and errors are shown in separate panels.
2. The panel for goals is not cleaned up when you remove the goal. It is only removed when a declaration, which contained a goal, has no more errors or other goals.
3. Implicit goals (goals without a corresponding `{?}` element in the source code) are not shown by default.
4. The vertical layout is supported.
5. UI has been improved a bit.

https://user-images.githubusercontent.com/5653229/149464671-becc1324-f405-4173-bcbc-4792be5a14f0.mp4
