### ISSUE TITLE
False negative "redundant parentheses" error

### ISSUE THREAD

**Issue by valis** [JetBrains/intellij-arend#339]
The warning isn't shown in the following code:
```
\func test => \Sigma (Nat) (Nat)
```

**Comment by valis** [comment]
A similar problem:
```
\func test => (Array Nat) -> (Array Nat)
```

**Comment by sxhya** [comment]
> A similar problem:
> 
> ```
> \func test => (Array Nat) -> (Array Nat)
> ```

Duplicate to #302
