### ISSUE TITLE
Improve UI around "Project SDK" field in the project wizard

### ISSUE THREAD

**Issue by marat-rkh** [JetBrains/intellij-arend#351]
![image](https://user-images.githubusercontent.com/5653229/150747985-d4d801b8-7ba8-418e-a95e-249ae996b3bc.png)

Project SDK is needed if you want to create a language extension or debug typechecking. It would be nice to add this information to the UI, say, it the form of [Inline help text](https://jetbrains.design/intellij/controls/inline_help_text/).

Also, `<No SDK>` is a valid option, so it should not be shown in the red color.

**Comment by marat-rkh** [comment]
Taken from #310.

**Comment by marat-rkh** [comment]
Agree. I failed to find an easy way to fix that, this logic is deeply hidden in the platform code. I will try to handle that later.

**Comment by sxhya** [comment]
> Agree. I failed to find an easy way to fix that, this logic is deeply hidden in the platform code. I will try to handle that later. Updated the description.

Here's the stacktrace pointing out to the code that is responsible for _actually_ painting that combo box item in red.
Doesn't seem very configurable to me.

![image](https://github.com/JetBrains/intellij-arend/assets/7237597/0ebcbf19-9157-4e80-b36f-d7ba265302f2)

**Comment by sxhya** [comment]
Won't fix.
