### ISSUE TITLE
Confusing error when infix constructor is used in pattern matching

### ISSUE THREAD

**Issue by marat-rkh** [JetBrains/intellij-arend#358]
<img width="1006" alt="Screen Shot 2022-02-14 at 12 35 49 PM" src="https://user-images.githubusercontent.com/5653229/153838168-9a414797-1fe7-4cc2-8e8b-02e4cc0364f1.png">

We cannot write a code like that because infix constructors in pattern matching must be used in the prefix form. We need to write `:: a l` instead. But if you do not know about that, it might be very confusing, and the error message doesn't help (and, arguably, confuses even more). 

I think it would make sense to provide a proper error message saying that the prefix form must be used.

**Comment by marat-rkh** [comment]
BTW, @valis, is there any specific reason why we cannot use the constructors in an infix form in patterns?

**Comment by knisht** [comment]
https://t.me/c/1273587349/5001

**Comment by ice1000** [comment]
Lmao! Ancient discussion

**Comment by knisht** [comment]
Fixed by implementing infix patterns.
