### ISSUE TITLE
"Change Argument Explicitness" adds redundant long name to local functions

### ISSUE THREAD

**Issue by marat-rkh** [JetBrains/intellij-arend#362]
```tex
\func foo => bar Nat nil
  \where {
    \func bar (A : \Type) (l : List A) => l
  }
```
Call `Change Argument Explicitness` on `(A : \Type)`, you will get:

```tex
\func foo => foo.bar {Nat} nil
  \where {
    \func bar {A : \Type} (l : List A) => l
  }
```
Note that now `bar` is replaced with `foo.bar`. The `foo.` prefix is redundant here, I always need to remove it after I apply the intention.

**Comment by sxhya** [comment]
Can't reproduce in the current version of Arend plugin.
