### ISSUE TITLE
Do not show "Traced declaration has typechecking errors" warning for declarations with goals and no errors

### ISSUE THREAD

**Issue by marat-rkh** [JetBrains/intellij-arend#364]
This warning is shown when you start tracing on a declaration with a goal. The warning makes no sense in that case.

**Comment by knisht** [comment]
Looks like I've accidentally fixed it in 82978e7bc244c28d04bef9a9bea1dda2acc3a1e0 :thinking:

**Comment by marat-rkh** [comment]
Oh, cool!
