### ISSUE TITLE
Proof search should be exclusive to Arend files

### ISSUE THREAD

**Issue by ice1000** [JetBrains/intellij-arend#367]
It's preventing me from "introduce parameter" in Java :rage:

**Comment by ice1000** [comment]
:angry: :angry: :angry: :angry: :angry: :angry:

**Comment by ice1000** [comment]
:angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry:

**Comment by knisht** [comment]
c72b4fa5eab7a1e797bee7ac5bf6a5c95ec71d5f

**Comment by ice1000** [comment]
:hugs: :hugs: :hugs: :hugs: :hugs: :hugs:
