### ISSUE TITLE
NullPointerException on type check

### ISSUE THREAD

**Issue by xamgore** [JetBrains/intellij-arend#38]
NPE occures while typechecking file [hw03.ard](https://hastebin.com/raw/obijilirip) (imports modified [lect03.ard](https://hastebin.com/raw/toqawineqi)). I run `Ctrl+Shift+F10` with mouse cursor set on a free line between definitions (like line 217). Full exception [stack trace](https://hastebin.com/raw/wufewulosi).

```java
java.lang.Throwable: [ERROR] An exception happened while persisting module: hw03
  java.lang.NullPointerException
	at org.arend.module.serialization.ExpressionSerialization.writeBindingRef
                                                 (ExpressionSerialization.java:77)
```

**Comment by valis** [comment]
Fixed in [11e001c](https://github.com/JetBrains/Arend/commit/11e001c332435c8a5fe8445847428104fdbcf545)
