### ISSUE TITLE
please publish Arend plugin for IDEA 2022.3 EAP

### ISSUE THREAD

**Issue by unkarjedy** [JetBrains/intellij-arend#384]
One of the users of IntelliJ IDEA [reported](https://discord.com/channels/931170831139217469/1044344345135947807/1044563572627349514) that after upgrading to IDEA 2022.3 EAP it broke his workflow with [Arend plugin]([https://](https://plugins.jetbrains.com/plugin/11162-arend)).

>It did break my Arend workflow because that plugin doesn't have a 2022.3 version yet..

Can we publish it for 2022.3 before the final release?

**Comment by valis** [comment]
Fixed
