### ISSUE TITLE
Issues with Arend completion

### ISSUE THREAD

**Issue by sxhya** [JetBrains/intellij-arend#391]
- [x] Decide if definitions from unimported Arend modules should be added into backup completion menu (`NoCompletionDelegator` mechanism). Currently they do appear in completion menu, but attempting to import them is always unsuccessful. If they should appear in completion the name of the unimported module should be highlighted in the completion menu and their import should actually lead to the containing module be imported.

- [x] It would be nice to have information from which Arend file/Arend module a definition appearing in completion comes from (in a similar fashion how it is currently happens in `Ctrl+N` menu). This can be done at least for `\data`'s or `\constructor`'s which do not have result type.

- [x] At the moment Arend will not autocomplete full name of an Arend file (when a user e.g. types an `\import`-command manually) if the user does not provide the folder prefix to it.

- [x] @valis requested support of \private and \protected keywords for NoVariantsDelegator

@valis What do you think?

**Comment by valis** [comment]
I don't understand the first bullet point. It imports just fine.

**Comment by sxhya** [comment]
No it does not. By Arend module I mean the entity you see in Project Structure dialog. Try creating new module in this dialog and then using stuff from `arend-lib`.
