### ISSUE TITLE
Disallow user from importing several Arend modules at once.

### ISSUE THREAD

**Issue by sxhya** [JetBrains/intellij-arend#409]
In the attached gif you can see that importing a directory with 2 Arend modules is allowed and that no errors are reported.

![Peek 2023-07-25 12-15](https://github.com/JetBrains/intellij-arend/assets/7237597/cfff7fa4-064e-4e9e-9564-e71bef148a51)

I propose to do the following.

Import Arend module feature should recursively scan for `arend.yaml` files in the folder tree. If no YAML-files are found, warning should be given to the user. If multiple YAML files are found, 1 Arend module should be created per each Yaml. The situation mentioned in the video should not happen.

**Comment by valis** [comment]
There should be just 1 yaml file in the root. No scanning is required.
