### ISSUE TITLE
NPE and checker crash

### ISSUE THREAD

**Issue by demiurg906** [JetBrains/intellij-arend#42]
Type checker "successfully" checks that code:
```
\data List (A : \Type) | nil | cons A (List A)

\func \infixl 4 ++ {A : \Type} (xs ys : List A) : List A \elim xs
  | nil => ys
  | cons x xs => cons x (xs ++ ys)

\func reverse {A : \Type} (xs : List A) : List A
  | nil => nil
  | cons x xs => reverse xs ++ cons x nil

\func ++nil {A : \Type} (xs : List A) : xs ++ nil = xs
    | nil => idp
    | cons x xs => pmap (\lam xs => cons x xs) (++nil xs)

-- Это утверждение будет полезно для доказательства.
\func reverse++ {A : \Type} (xs ys : List A) : reverse (xs ++ ys) = reverse ys ++ reverse xs \elim xs
    | nil => sym (++nil (reverse ys))
    | cons x xs => pmap (\lam list => list ++ (cons x nil)) {?}
```

![](https://user-images.githubusercontent.com/14974409/46745659-2b74f700-ccb6-11e8-9bb0-6608cb239345.png)

P.S. check test time

**Comment by valis** [comment]
I cannot reproduce this bug. Could you try to typecheck this code on the latest version of the plugin?

**Comment by demiurg906** [comment]
Still fails

Here sources and stacktrace (fail in hw05_copy)

[stacktrace.log](https://github.com/JetBrains/intellij-arend/files/2468847/stacktrace.log)
[hw05_copy.ard.txt](https://github.com/JetBrains/intellij-arend/files/2468852/hw05_copy.ard.txt)
[lect05.ard.txt](https://github.com/JetBrains/intellij-arend/files/2468853/lect05.ard.txt)

**Comment by valis** [comment]
I still cannot reproduce it. Try to delete .output directory.

**Comment by xamgore** [comment]
@demiurg906, what version of IDEA do you use?

**Comment by demiurg906** [comment]
> I still cannot reproduce it. Try to delete .output directory.

It helps
