### ISSUE TITLE
Feature: swap parameters

### ISSUE THREAD

**Issue by xamgore** [JetBrains/intellij-arend#44]
![image](https://user-images.githubusercontent.com/4586392/47175100-feaa8a80-d31a-11e8-9ac2-1917c91aee17.png)

It is a common task to swap parameters with each other on infix operators. `=`, `+`, etc. It would be nice, if the plugin suggested to swap it for you (by pressing Alt+Enter for example).

**Comment by mmagic-boy** [comment]
This one can be closed (#262).

**Comment by ice1000** [comment]
> This one can be closed (#262).

I think you can just close it

**Comment by xamgore** [comment]
@mmagic-boy nice work, thank you!
