### ISSUE TITLE
Ctrl+W broken

### ISSUE THREAD

**Issue by sxhya** [JetBrains/intellij-arend#454]
![Bug_In_CtrlW](https://github.com/JetBrains/intellij-arend/assets/7237597/932fefe5-0a96-4db4-8cd8-e7d130f04891)

**Comment by ice1000** [comment]
😱😱😱😱 a workaround can be using the show type action to select a piece of expression with range calculated by the compiler.

**Comment by sxhya** [comment]
Can't reproduce
