### ISSUE TITLE
Multi-level comment braces conflict LaTeX tags.

### ISSUE THREAD

**Issue by sxhya** [JetBrains/intellij-arend#469]
In LaTeX you often write $a^{-1}$ (i.e. `a^{-1}`) but this conflicts with multi-level comment brace feature (e.g. that you may write several nested comment braces {- ... {- ... -} ... -}. 

- [ ] Mutli-level comment brace should be disabled within LaTeX tags. 
- [ ] Use special color highlighting for code within LaTeX $ and $$ tags.

**Comment by ice1000** [comment]
Maybe do `a^{ -1}`?

**Comment by sxhya** [comment]
won't fix
