### ISSUE TITLE
Support 2024.2?

### ISSUE THREAD

**Issue by ice1000** [JetBrains/intellij-arend#519]

**Comment by ice1000** [comment]
2024.2 is released!

**Comment by 6e69636b** [comment]
Is your issue that Arend is not available for 2024.2? That is the experience I am having. I am unable to find exactly which versions of IntelliJ IDEA Arend is available for as a plugin. Is there a list somewhere I've overlooked? Thanks.

**Comment by ice1000** [comment]
> Is your issue that Arend is not available for 2024.2? That is the experience I am having. I am unable to find exactly which versions of IntelliJ IDEA Arend is available for as a plugin. Is there a list somewhere I've overlooked? Thanks.

It's currently on 2024.1 or 2024.1.x
