### ISSUE TITLE
Fix menu elements for modules in usages view

### ISSUE THREAD

**Issue by sxhya** [JetBrains/intellij-arend#54]
Arend modules are not listed in the structured view of usages. There should be both an icon (m) and a properly named menu element for them.

**Comment by part-xx** [comment]
Added (m) icons for modules. Implemented structured view scheme for FindUsages: file -- definition -- usage. Note that under this scheme modules are not typically shown in FindUsages. (m) icons show up in e.g. caller/callee hierarchies (Ctrl-Alt-H).
