### ISSUE TITLE
instance parameters are not resolved in the editor

### ISSUE THREAD

**Issue by Odomontois** [JetBrains/intellij-arend#57]
In the instance body some parameters are not resolved by the plugin and shown as unresolved reverence 

Examples : 
https://github.com/manatki/manatki/blob/0a6d528e1eb58de227cc317783c11c78185d3354/proofs/src/monad/std.ard#L17

![image](https://user-images.githubusercontent.com/247558/53745807-cca45a00-3eb0-11e9-82a8-5f718d71bd42.png)

https://github.com/manatki/manatki/blob/08cf24fc767ce2fe0e0863865fe9fa397f4b4496/proofs/src/monad/wire.ard#L39

![image](https://user-images.githubusercontent.com/247558/53745856-ef367300-3eb0-11e9-96b9-73734ac56cb6.png)

**Comment by valis** [comment]
Fixed in [5240210](https://github.com/JetBrains/Arend/commit/524021016c73940263f8df3c9a2f0d1ab23eb4a2).
