### ISSUE TITLE
Confusing error when trying to overload constructor

### ISSUE THREAD

**Issue by andreasabel** [JetBrains/intellij-arend#58]
I am trying to learn your nice little dependently-typed language.

Attempting to overload a constructor Agda-style,
```arend
\data List (A : \Type)
  | nil
  | \infixr 6 :: A (List A)

\data Sublist {A : \Type} (xs ys : List A) \elim xs, ys
  | nil, nil => nil
```
I get a confusing error message:
```
[ERROR] ...:7:5: 'nil' is not a constructor of data type List A
  In: nil
  While processing: Sublist
```
Well, in fact, 'nil' **is** a constructor of data type List. :)

**Comment by valis** [comment]
The 'nil' it refers to is not a constructor of List (it gives a reference and not just a name). It also produces a warning (at least in the new version) about conflicting names.

**Comment by sxhya** [comment]
@valis, Don't you also want to modify the behavior of scopes so that the constructors of a datatype defined via pattern matching would not be visible inside its patterns?

**Comment by valis** [comment]
@sxhya No, this contradicts the general scoping rules. This would mean that constructors of a datatype are visible _everywhere_ except its own patterns.

**Comment by sxhya** [comment]
As you wish, but to me the behavior you describe makes more sense actually.
