### ISSUE TITLE
Infix notation not supported in patterns

### ISSUE THREAD

**Issue by andreasabel** [JetBrains/intellij-arend#59]
```arend
\data List (A : \Type)
  | nil
  | \infixr 6 :: A (List A)

\func append {A : \Type} (xs ys : List A) : List A
  | nil, ys => ys
  | (x :: xs), ys => x :: append xs ys
```
This gives the error:
```
[ERROR] ....ard:8:6: Cannot resolve reference 'x'
  While processing: append
```
Maybe the documentation on patterns should say that infix is not supported in patterns.

**Comment by valis** [comment]
Infix notation is not supported in patterns and the documentation gives a complete description of how patterns can be described, which excludes infix notation.
