### ISSUE TITLE
\elim cannot be nested!?

### ISSUE THREAD

**Issue by andreasabel** [JetBrains/intellij-arend#61]
Can `\elim` not be nested?
```arend
\data List (A : \Type)
  | nil
  | \infixr 6 :: A (List A)

\data Sublist {A : \Type} (xs ys : List A) \elim xs
  | nil        => sub-nil
  | (:: x xs)  => {\elim ys 
    | (:: y ys)  => {
      | sub-cons (x = y) (Sublist xs ys)
      | sub-wk (Sublist (x :: xs) ys)
    }}
```
This gives the following error at `(:: y ys)`:
```
[ERROR] <file>.ard:7:3: Incomplete expression
  While processing: Sublist
```

**Comment by valis** [comment]
Yes, \elim cannot be nested.

**Comment by andreasabel** [comment]
But the error message given to the user is incomprehensible and does not point at the heart of the problem.  I expect an error like `\elim cannot appear here` or so.

**Comment by valis** [comment]
It's a parser error, which are shown in the editor. We do not copy them to the typechecker output. In the new version of the plugin, all of the errors are shown in the editor, so this should be more acceptable.
