### ISSUE TITLE
Case split chooses unsafe names

### ISSUE THREAD

**Issue by rjmk** [JetBrains/intellij-arend#73]
Consider the code

```
\data Foo
  | Foo Nat Nat

\func bar (n : Foo) : Foo
```

If I try and get the necessary case match from `alt`-`shift`-`enter`, I'll end up with

```
\data Foo
  | Foo Nat Nat

\func bar (n : Foo) : Foo
  | Foo.Foo n n => {?}
```

The plugin both chooses a name that's not available (`n`) and it chooses that same name twice, which could never work

**Comment by sxhya** [comment]
1) I checked this on current master version and got the following correct output:
`\data Foo
  | Foo Nat Nat

\func bar (n : Foo) : Foo
  | Foo.Foo n n1 => {?}`
So apparently you have encountered a problem which have already been fixed and you are using packaged plugin version which is not up do date (we will update it ASAP).
2) Also notice that the first usage of "n" is a perfectly legal one (in Arend function parameters are not visible after they are pattern-matched). You may check this behavior as follows: rename "n n1" to "n1 n2" and notice that the first "n" is still not visible inside the clause expression.
