### ISSUE TITLE
Renaming does not work

### ISSUE THREAD

**Issue by valis** [JetBrains/intellij-arend#79]
Rename `SetSpec` to anything. The class itself will be renamed, but not its occurrence in foo.

```
\data Empty

\class SetSpec (S : \Set -> \Set)
  | empty {A : \Set} : S A
  | add {A : \Set} : A -> S A -> S A
  | isElem {A : \Set} : A -> S A -> \Prop
  | setExt {A : \Set} (s1 s2 : S A) (p : \Pi (x : A) -> x `isElem` s1 = x `isElem` s2) : s1 = s2
  | emptyProp {A : \Set} (e : A) : e `isElem` empty -> Empty
  | addHead {A : \Set} (x : A) (s : S A) : x `isElem` add x s
  | addTail {A : \Set} (e x : A) (s : S A) : e `isElem` s -> e `isElem` add x s

\func foo (S : \Set -> \Set) {_ : SetSpec S} => {?}
```

**Comment by valis** [comment]
In the following code, `branch` and `leaf` do not resolve properly. This bug may be difficult to reproduce. Sometimes everything works correctly, but if I remove the definition of `Tree` and paste it again, it breaks. I think this is related to the caching of resolved references.

```
\data Tree
  | leaf
  | branch Tree Tree

\func foo (d : Tree) : Nat
  | leaf => 0
  | branch t1 t2 => 1
```

**Comment by sxhya** [comment]
I was unable to reproduce the problem from your comment. However, disabling ArendResolveCache does not resolve the original issue so I suspect that the original problem is unrelated to the resolve cache.

**Comment by valis** [comment]
When I say "do not resolve properly", I mean that you cannot do "go to", "rename", and other refactorings, but everything type-checks normally.

**Comment by sxhya** [comment]
Can't reproduce the original issue. Please comment whether you still can reproduce it.
