### ISSUE TITLE
Improve TypeCheckRunConfigurationEditor

### ISSUE THREAD

**Issue by mchernyavsky** [JetBrains/intellij-arend#8]
1. No gui controls in "Create new Arend project" window

2. Want to have smarter Run Configuration gui controls for typechecking arend definitions
Want to have list of all definitions in completion list (replace TextBox'es with smarter controls) -- see RunConfiguration for Groovy

**Comment by valis** [comment]
There are GUI controls in other places for which this feature will be useful.

**Comment by sxhya** [comment]
@valis, is there anything left to be done from this issue? Can it be closed now?
